### ISSUE TITLE
Possible Error during current_state update

### ISSUE THREAD

**Issue by russointroitoa** [Skybox-Technologies/csgo-ai-competition#1]
Dear Organizers, 

Exploring the dataset, I noticed an inversion of the meaning of _current_state_ position values: in the description of the data format, it is explained that the first position of _current_state_ refers to _CT_ and the second position to _Terrorist_.
Considering _dftrain_ in the notebook provided, the first round goes from index 0 to 3 where the  _round_winner = CT_, such that in the next round (starting from index 4) the victory point needs to be assigned to CT; however, the point is assigned to the second position of _current_score_, that is _Terrorist_.
Moreover, there is another inversion in the meaning of _current_state_: the round defined from row index 76 to 79 is won by CT and the second position in _current_state_ is incremented, following the same approach so far. The next round (from row index 80 to 83) is won by _Terrorist_, but always the second position of _current_state_ is incremented.

I would like to know if I'm missing something or this is a real issue.

**Comment by kristoff3r** [comment]
Hey,

That looks like a bug in the dataset generator. I'll investigate it when I get time next week, thanks for reporting it.

**Comment by kristoff3r** [comment]
It is a bug in the dataset. I'll be updating the dataset with the correct values sometime next week.

**Comment by russointroitoa** [comment]
Sorry, I think that the error is still present in the second version of the dataset. 
 
![Schermata 2020-05-12 alle 17 25 45](https://user-images.githubusercontent.com/44086129/81713438-27065680-9476-11ea-8cf9-7a4815ac3d4d.png)

**Comment by kristoff3r** [comment]
@russointroitoa  Isn't that due to the half time switch, or am I missing something?

**Comment by russointroitoa** [comment]
Ok, I didn't realize the half time switch, now I understand the logic! 
Thanks!
