### ISSUE TITLE
"World" kills question

### ISSUE THREAD

**Issue by andrew-son** [Skybox-Technologies/csgo-ai-competition#12]
As far I understand, "World" kills are mostly round restart kills (like in entries with 10 team-kills in `previous_kills` with `attacker_side` and `attacker_position` fields present; positions seems to be spawns) or self-kills (in that case `attacker_side` and `attacker_position` fields are `None`). However, one snapshot differs from both cases (index 68121 in combined dataset). It has both `attacker_side` and `attacker_position` fields set and the position is not a spawn position (tunnel stairs to be exact). Is it a bug? Can we just safely omit all the  "World" kills except ones with  `None` `attacker_side` and `attacker_position` fields, which seems to indicate a self-kill (e.g. from fall damage, not sure if `trigger_hurt` on maps like vertigo counts)

**Comment by kristoff3r** [comment]
All examples of this in the dataset are suicides (i.e. attacker and victim are the same player), which can happen when you type "kill" in the console or when players crash/disconnect when they are alive. We already filter rounds which were restarted, so either this happened and had direct impact on the match, or our heuristic for filtering missed an edge case.

I'll go through the cases and see if I can figure it out. I'll probably also filter kills in freezetime, as they are usually match medic type of stuff.

**Comment by andrew-son** [comment]
@kristoff3r If it somehow helps: basically what I did was filtering all rounds with kills more than 10 and I found out entries with like 10 kills at spawn points so I thought that's trailing suicide kills from round restarts (since they were marked as team kills)
