### ISSUE TITLE
Errors in submission

### ISSUE THREAD

**Issue by szelesaron** [Skybox-Technologies/csgo-ai-competition#17]
I just used the submission page but I got several errors even though I used the exact format that was asked and included all the files in the zip file. Any solution?

**Comment by kristoff3r** [comment]
Your zip file should not contain a submission folder, it needs to be flat. See `pack_submission.sh` for how to pack it.

**Comment by szelesaron** [comment]
Now I got this message:

**The README file is missing. You need to include either README.txt or README.md (case matters) at the top level**

But I did include a README.txt file.

**Comment by kristoff3r** [comment]
You called the file README.txt.txt, try enabling "Show extensions for known filetypes" if you're on Windows.

**Comment by szelesaron** [comment]
For the first time, I submitted it without the extension, but it gave me the same message.

**Comment by kristoff3r** [comment]
@szelesaron ah, there was a bug in my checker, can you try uploading the first one again?

**Comment by szelesaron** [comment]
Now I got this message ony:

**/tmp/csgo_ai.1Vcpx07inR ~/csgo-ai**
And in the valid format column it still says false.

**Comment by kristoff3r** [comment]
Weird, I'll look into it. I'll mark the current one as valid, thanks for testing :D

**Comment by szelesaron** [comment]
Cheers mate.
