### ISSUE TITLE
samples with more than 50 position_history values, implying round time of > 4 minutes

### ISSUE THREAD

**Issue by MiniXC** [Skybox-Technologies/csgo-ai-competition#4]
In the readme **position_history** is described as
````Previous positions for this player in the round, sampled every 5 seconds (but not in freezetime)````
A few samples in the dataset have a position_history with more than 50 values, which would imply a round time of more than 4 minutes... How is this possible?

Edit: There are 425 samples with ``round_status_time_left=-1``, will we have to predict rounds that have already finished, or does -1 mean something else?

**Comment by kristoff3r** [comment]
The samples with -1 are paused in freezetime, I'll filter them out when I update the dataset.
