### ISSUE TITLE
bomb plant time leak

### ISSUE THREAD

**Issue by MiniXC** [Skybox-Technologies/csgo-ai-competition#5]
![image](https://user-images.githubusercontent.com/3523501/81481897-35acfd80-922b-11ea-85e5-f98f2e5c9fba.png)
There is a time leak in the current dataset. The bomb plant & position is always present, even during freeze time (see picture). This feature gives a basic model ~0.83 accuracy because it can tell if the bomb will be planted eventually from this feature.

**Comment by kristoff3r** [comment]
Oops, that's pretty bad. I'll fix this (and the other stuff) and push a new version monday, thanks for reporting.
